--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/9/2022 2:08:52 PM
-- Server version: 8.0.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE motel;

--
-- Drop table `bill`
--
DROP TABLE IF EXISTS bill;

--
-- Drop table `billdetail`
--
DROP TABLE IF EXISTS billdetail;

--
-- Drop table `comment`
--
DROP TABLE IF EXISTS comment;

--
-- Drop table `history`
--
DROP TABLE IF EXISTS history;

--
-- Drop table `room`
--
DROP TABLE IF EXISTS room;

--
-- Drop table `userapp`
--
DROP TABLE IF EXISTS userapp;

--
-- Set default database
--
USE motel;

--
-- Create table `userapp`
--
CREATE TABLE userapp (
  UserID char(36) NOT NULL DEFAULT '',
  FullName varchar(255) DEFAULT NULL,
  UserName varchar(255) DEFAULT NULL,
  Password varchar(255) DEFAULT NULL,
  Email varchar(50) DEFAULT NULL,
  Phone varchar(20) DEFAULT NULL,
  UserType int DEFAULT NULL,
  IsDeleted bit(1) DEFAULT NULL,
  CreatedDate timestamp NULL DEFAULT NULL,
  ModifiedDate timestamp NULL DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Lưu thông tin người dùng';

--
-- Create table `room`
--
CREATE TABLE room (
  RoomID char(36) NOT NULL DEFAULT '',
  Province varchar(255) DEFAULT NULL,
  District varchar(255) DEFAULT NULL,
  Ward varchar(255) DEFAULT NULL,
  Address longtext DEFAULT NULL,
  Area varchar(255) DEFAULT NULL,
  Price int DEFAULT NULL,
  Status int DEFAULT NULL,
  UserID char(36) DEFAULT NULL,
  HostID char(36) DEFAULT NULL,
  Content longtext DEFAULT NULL,
  PublishDate timestamp NULL DEFAULT NULL,
  IsDeleted bit(1) DEFAULT NULL,
  CreatedDate timestamp NULL DEFAULT NULL,
  ModifiedDate timestamp NULL DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (RoomID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `history`
--
CREATE TABLE history (
  HistoryID char(36) NOT NULL DEFAULT '',
  UserID char(36) DEFAULT NULL,
  HostID char(36) DEFAULT NULL,
  RoomID char(36) DEFAULT NULL,
  TimeCheckOut timestamp NULL DEFAULT NULL,
  PriceRoom int DEFAULT NULL,
  IsDeleted bit(1) DEFAULT NULL,
  CreatedDate timestamp NULL DEFAULT NULL,
  ModifiedDate timestamp NULL DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (HistoryID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `comment`
--
CREATE TABLE comment (
  CommentID char(36) NOT NULL DEFAULT '',
  RoomID char(36) DEFAULT NULL,
  UserID char(36) DEFAULT NULL,
  Content longtext DEFAULT NULL,
  Rate int DEFAULT NULL,
  IsDeleted bit(1) DEFAULT NULL,
  CreatedDate timestamp NULL DEFAULT NULL,
  ModifiedDate timestamp NULL DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (CommentID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `billdetail`
--
CREATE TABLE billdetail (
  BillDetailID char(36) NOT NULL DEFAULT '',
  RoomID char(36) DEFAULT NULL,
  UserID char(36) DEFAULT NULL,
  PriceRoom int DEFAULT NULL,
  PriceElectric int DEFAULT NULL,
  PriceWater int DEFAULT NULL,
  PriceSevice int DEFAULT NULL,
  IsDeleted bit(1) DEFAULT NULL,
  CreatedDate timestamp NULL DEFAULT NULL,
  ModifiedDate timestamp NULL DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (BillDetailID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `bill`
--
CREATE TABLE bill (
  BillID char(36) NOT NULL DEFAULT '',
  Status int DEFAULT NULL,
  UserID char(36) DEFAULT NULL,
  HostID char(36) DEFAULT NULL,
  IsDeleted bit(1) DEFAULT NULL,
  CreatedDate timestamp NULL DEFAULT NULL,
  ModifiedDate timestamp NULL DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (BillID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table userapp
--
-- Table motel.userapp does not contain any data (it is empty)

-- 
-- Dumping data for table room
--
-- Table motel.room does not contain any data (it is empty)

-- 
-- Dumping data for table history
--
-- Table motel.history does not contain any data (it is empty)

-- 
-- Dumping data for table comment
--
-- Table motel.comment does not contain any data (it is empty)

-- 
-- Dumping data for table billdetail
--
-- Table motel.billdetail does not contain any data (it is empty)

-- 
-- Dumping data for table bill
--
-- Table motel.bill does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;